language: node_js
node_js:
- '5'
- '5.1'
- '4'
- '4.2'
- '4.1'
- '4.0'
- '0.12'
deploy:
  provider: npm
  email: hpe-idol-oss@groups.ext.hpe.com
  api_key:
    secure: KUoakM8XA+RZ6L1VUscAveRunX0F8bfwE4/9gXAlM4jOOWIixI2xq7CVe+n/4Dtq30EEnrwcL02ropLrSHpCGg1zlu0hbPkk1lms9vpt/8dEoQ4o/FAhXcP3OB7O8YyvMbk0BuRebxdx3+KImJmk/f93+/YFX0Rar8cKXGqK7nmJJ+LBAxhvchPVgMdpD0J/6SZ8Rg/KLMt11roc6wzcpcEF/MnLbmnFWy4lVKh5P+1ryh8m9tSgc2+LRbkLCXEvvQnKn4hdiRN/TgTngOktJZF2k5iZvt5hPbWw5Z2n2sWiy65GRwCalLDf8SQbjJPqOFgXGy+mnby9x9/aznp5x3rQQwjmuZMyhye/NGneJ9McQCedRValJ2+KzinlHJh9OSWM/nymT0WxLLKvP07wO2uK3xPNN2MIyrJQvwcJMtqS8N8uhuDN7QmOhhGOlrhcnexE8SCYZf2jyfspMeYvYmGunmNOlIjhsDaT3IUccVJ5AG7IrVWXCrfXKMPHseWOxv3zKZNs4t+oaVp7JpKO8VeWhQSTaTH1cF66lSWaO+B9HTQrefqDtu5+deL5eF2uThy9GaTRcrmmoPUJ3A/f8QTPr0sOKV13ma6JWeU1xGGJRzYGH8NWrVrJ65jTlIXQTtyNZQemAcs2mrMgQ40wuHVB0bMehkAUKbeUgHsThUY=
  on:
    branch: master
    tags: true
    repo: hpe-idol/express-hod-sso
